version: '3.3'
services:
  database:
    image: mysql:8.0
    container_name: shopping-db
    command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=shopping-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - dbdata:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3011:3306
    stdin_open: true
    tty: true
    restart: always
  app:
    container_name: shopping-app
    build:
      context: ./docker/php/
      args:
        - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./src:/work/app:delegated
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/ash:/etc/profile.d
      - ./docker/php/psysh:/root/.config/psysh
      - ./docker/php/supervisord.conf:/etc/supervisord.conf
      - ./docker/php/supervisord.d:/etc/supervisord.d
    working_dir: /work/app
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    # entrypoint: ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

  nginx:
    image: nginx:1.19.10
    depends_on:
      - app
    container_name: shopping-nginx-prod
    ports:
      - 443:443
      - 8081:8080
    volumes:
      - ./src:/work/app:delegated
      - ./logs:/var/log/nginx
      - ./docker/nginx/nginx_prod.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - COMPOSE_PROJECT_NAME=app
    command: /bin/sh -c "envsubst '$$COMPOSE_PROJECT_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
volumes:
  dbdata:



